apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.name" . }}
  labels: {{ include "webapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels: {{ include "webapp.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "webapp.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-migration
        image: groundnuty/k8s-wait-for:v1.4
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        args: ["job", "{{ include "webapp.migrator" . }}"]
      containers:
      - name: webapp
        image: {{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        env:
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: {{ include "webapp.name" . }}
              key: connectionString
        ports:
        - containerPort: 80
