apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webapp.migrator" . }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels: {{ include "webapp.migrator.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-postgres
        image: groundnuty/k8s-wait-for:v1.4
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        args: ["service", "{{ include "webapp.postgres" . }}"]
      containers:
      - name: migrator
        image: {{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        env:
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: {{ include "webapp.name" . }}
              key: connectionString
        command: ["dotnet", "WebApplication.Migrator.dll"]
      restartPolicy: Never
