apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webapp.name" . }}
data:
  {{- $host := printf "Host=%s" (include "webapp.postgres" .) }}
  {{- $database := .Values.webapp.database.name }}
  {{- $username := .Values.webapp.database.username }}
  {{- $password := .Values.webapp.database.password | b64dec }}
  connectionString: {{ printf "%s;Database=%s;Username=%s;Password=%s" $host $database $username $password | b64enc }}