version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U webapp" ]
      interval: 5s
      timeout: 5s
      retries: 5
