postgres:
  image:
    repository: postgres
    tag: latest
    pullPolicy: IfNotPresent
  volume:
    hostPath: /opt/webapp/db
  nodeSelector:
    storage: enabled
  credentials:
    username: webapp
    password: d2ViYXBw

webapp:
  replicas: 1
  image:
    repository: mariuszba/webapp
    tag: latest
    pullPolicy: IfNotPresent
  database:
    name: webapp
    username: webapp
    password: d2ViYXBw

ingress:
  host: webapp.mariush.pl
  
issuers:
  env: staging
  staging:
    email: example@mail.com
  prod:
    email: example@mail.com
