apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrator-{{ .Release.Revision }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrator
    spec:
      initContainers:
      - name: migrator-init
        image: groundnuty/k8s-wait-for:v1.4
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        args: ["pod", "-lapp={{ .Release.Name }}-postgres-db"]
      containers:
      - name: migrator
        image: {{ .Values.webapp.image.repository }}:{{ .Values.webapp.image.tag }}
        imagePullPolicy: {{ .Values.webapp.image.pullPolicy }}
        env:
        - name: ConnectionStrings__Database
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-webapp-secret
              key: connectionString
        command: ["dotnet", "WebApplication.Migrator.dll"]
      restartPolicy: Never
